## Матрицы и матричные операции. Часть 1.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [36]:
import numpy as np

In [37]:
a = np.array([[1, -2], [3, 0]])

b = np.array([[4, -1], [0, 5]])

In [38]:
print(f'Сумма матриц A и B-\n {a + b}.')

Сумма матриц A и B-
 [[ 5 -3]
 [ 3  5]].


In [39]:
print(f'Произведение матриц A и B-\n {a.dot(b)}.')

Произведение матриц A и B-
 [[  4 -11]
 [ 12  -3]].


In [40]:
print(f'Произведение матриц B и A-\n {b.dot(a)}.')

Произведение матриц B и A-
 [[ 1 -8]
 [15  0]].


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [41]:
a = np.array([[1, 7], [3, -6]])

b = np.array([[0, 5], [2, -1]])

c = np.array([[2, -4], [1, 1]])

In [42]:
print(f'Линейная комбинация 3A-2B+4C равна\n{3*a-2*b+4*c}.')

Линейная комбинация 3A-2B+4C равна
[[ 11  -5]
 [  9 -12]].


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [43]:
a = np.array([[4, 1], [5, -2], [2, 3]])

In [44]:
a_trans = a.T

a_trans

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [45]:
a.dot(a_trans)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [46]:
a_trans.dot(a)

array([[45,  0],
       [ 0, 14]])

## Матрицы и матричные операции. Часть 2.

__1.__ Вычислить определитель:

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [47]:
from numpy import linalg

In [48]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

In [49]:
print(f'Определитель матрицы равен {np.linalg.det(a)}.')

Определитель матрицы равен 180.0.


 в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [50]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [51]:
print(f'Определитель матрицы равен {np.linalg.det(b):.0f}.')

Определитель матрицы равен 0.


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [52]:
c = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

In [53]:
print(f'Определитель матрицы равен {np.linalg.det(c):.0f}.')

Определитель матрицы равен 0.


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [54]:
d = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

In [55]:
print(f'Ранг матрицы равен {np.linalg.matrix_rank(d)}.')

Ранг матрицы равен 2.


б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [56]:
e = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

In [57]:
print(f'Ранг матрицы равен {np.linalg.matrix_rank(e)}.')

Ранг матрицы равен 3.
